@startuml
Detector -> Proxy: new documents
Proxy -> Mturk: HITs
Main -> Proxy: processReviewable
Proxy -> Mturk: listReviewables
Mturk -> Proxy: hitIds
Proxy -> Mturk: listAssignmentsForHit
Mturk -> Proxy: assignments
Proxy -> Mturk: approve&reject
Proxy -> Main: results
Main -> Exporter: results
@enduml