import com.sumsubstance.*;

import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) throws Exception {
        Env.register(Detecter.class);
        Env.register(Proxy.class);
        Env.register(Exporter.class);
        Env.init();

        ScheduledExecutorService e = Executors.newScheduledThreadPool(2);
        e.schedule(()-> Env.get(Detecter.class).scan(), 10, TimeUnit.SECONDS);
        e.schedule(() -> Env.get(Exporter.class).export(Env.get(Proxy.class).processReviewablesHits()), 10, TimeUnit.SECONDS);
    }
}
